name: Reload GCP Terraform
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
    - templates/gcp/**
jobs:
  develop:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update Terraform
        uses: cloudify-cosmo/execute-workflow-action@v1.1
        with:
          environment-name: $EAAS_DEPLOYMENT_ID
          workflow: "execute_operation"
          parameters-file: ".github/inputs/reload-gcp-tf-params.json"

env:
  CLOUDIFY_HOST: ${{ secrets.CLOUDIFY_HOST }}
  CLOUDIFY_USERNAME: ${{ secrets.CLOUDIFY_USERNAME }}
  CLOUDIFY_PASSWORD: ${{ secrets.CLOUDIFY_PASSWORD }}
  CLOUDIFY_TENANT: ${{ secrets.CLOUDIFY_TENANT }}
  EAAS_DEPLOYMENT_ID: ${{ secrets.EAAS_DEPLOYMENT_ID }}
  CLOUDIFY_SSL: ${{ secrets.CLOUDIFY_SSL }}
  CLOUDIFY_SSL_TRUST_ALL: ${{ secrets.CLOUDIFY_SSL_TRUST_ALL }}
